(define (even? n)
    (= (remainder n 2) 0))
(define (double n) (+ n n))
(define (halve n) (quotient n 2))
(define (* a b)
    (cond ((= b 1) a )
          ((= b 0) 0)
          ((even? b) (double (* a (halve b))))
          (else (+ a (* a (- b 1))))))
            
(display (* 4 40)) (newline)
(display (* 5 76)) (newline)
(display (* 8 3)) (newline)
(display (* 9 9)) (newline)
(display (* 5 5)) (newline)
(display (* 0 0)) (newline)
